import os
from fpdf import FPDF
from datetime import datetime

UPLOAD_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "uploads", "documents")

class PDF(FPDF):
    def header(self):
        # Logo/Brand
        self.set_font("Arial", "B", 16)
        self.set_text_color(225, 29, 72) # Rose color
        self.cell(0, 10, "NestFind", 0, 1, "L")
        
        # Line
        self.set_draw_color(200, 200, 200)
        self.line(10, 20, 200, 20)
        self.ln(10) # Generous spacing

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")

def ensure_upload_dir():
    os.makedirs(UPLOAD_DIR, exist_ok=True)

def generate_reservation_booking(buyer_name, property_title, property_id, token_amount, offer_amount, property_address="[Address]"):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Header Title
    pdf.set_y(10)
    pdf.set_font("Arial", "B", 18)
    pdf.set_text_color(139, 92, 246)  # Purple color
    pdf.cell(0, 15, "BOOKING RESERVED", 0, 1, "C")
    pdf.ln(5)
    
    # Status Badge
    pdf.set_fill_color(220, 252, 231)  # Light green
    pdf.rect(70, pdf.get_y(), 60, 12, 'F')
    pdf.set_font("Arial", "B", 11)
    pdf.set_text_color(22, 163, 74)  # Green
    pdf.cell(0, 12, "PAYMENT CONFIRMED", 0, 1, "C")
    pdf.ln(10)
    
    # Content
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 10, f"Dear {buyer_name},", 0, 1)
    pdf.ln(5)
    
    pdf.multi_cell(0, 7, f"Congratulations! Your booking token has been successfully processed. The property '{property_title}' is now EXCLUSIVELY RESERVED for you.")
    pdf.ln(10)
    
    # Property Details
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "RESERVATION DETAILS:", 0, 1)
    pdf.line(10, pdf.get_y(), 120, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(50, 8, "Property:", 0, 0)
    pdf.set_font("Arial", "B", 11)
    pdf.multi_cell(0, 8, property_title)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(50, 8, "Location:", 0, 0)
    pdf.cell(0, 8, property_address, 0, 1)
    
    pdf.cell(50, 8, "Property ID:", 0, 0)
    pdf.cell(0, 8, f"#{property_id}", 0, 1)
    pdf.ln(5)
    
    # Payment Details
    pdf.set_fill_color(249, 250, 251)
    pdf.rect(10, pdf.get_y(), 190, 35, 'F')
    pdf.set_xy(15, pdf.get_y() + 5)
    
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "PAYMENT SUMMARY:", 0, 1)
    pdf.set_x(15)
    
    pdf.set_font("Arial", "", 10)
    pdf.cell(80, 7, "Offer Amount:", 0, 0)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 7, f"INR {offer_amount:,.0f}", 0, 1)
    pdf.set_x(15)
    
    pdf.set_font("Arial", "", 10)
    pdf.cell(80, 7, "Token Paid (0.1%):", 0, 0)
    pdf.set_font("Arial", "B", 10)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(0, 7, f"INR {token_amount:,.0f} (PAID)", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_x(15)
    
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 7, f"Payment Date: {datetime.now().strftime('%d %B, %Y %H:%M')}", 0, 1)
    pdf.ln(10)
    
    # Next Steps
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "NEXT STEPS:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.ln(2)
    
    steps = [
        "1. The seller will schedule the registration date",
        "2. You'll need to pay the platform commission (0.9% of property value)",
        "3. Complete the document verification process",
        "4. Finalize the registration and receive your property!"
    ]
    
    for step in steps:
        pdf.cell(0, 7, step, 0, 1)
    
    pdf.ln(10)
    
    # Important Notice
    pdf.set_fill_color(254, 249, 195)  # Light yellow
    pdf.rect(10, pdf.get_y(), 190, 25, 'F')
    pdf.set_xy(15, pdf.get_y() + 5)
    
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 7, "IMPORTANT:", 0, 1)
    pdf.set_x(15)
    pdf.set_font("Arial", "", 9)
    pdf.multi_cell(180, 5, "This property is now removed from the public marketplace and reserved exclusively for you. Keep this certificate safe for the registration process.")
    pdf.ln(15)
    
    # Footer
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, f"Document ID: RSV-{property_id}-{int(datetime.now().timestamp())} | Generated by NestFind", 0, 1, "C")
    
    filename = f"reservation_booking_{property_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"

def generate_offer_letter(buyer_name, property_title, property_id, amount, agent_name="NestFind Agent", property_address="[Address]"):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Header Title (Top Right)
    # Move cursor to top right for the title
    pdf.set_y(10)
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "OFFER ACCEPTANCE", 0, 1, "R")
    pdf.ln(10)
    
    # Content
    pdf.set_font("Arial", "", 11)
    
    # Subject
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 10, f"SUBJECT: Provisional Acceptance of Offer for {property_title}", 0, 1)
    pdf.ln(5)
    
    # Body
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 10, f"Dear {buyer_name},", 0, 1)
    pdf.ln(5)
    
    pdf.multi_cell(0, 7, f"We are pleased to inform you that the Seller has accepted your offer for the property located at {property_address}.")
    pdf.ln(5)
    
    pdf.multi_cell(0, 7, "This document serves as a provisional agreement. To secure this property and mark it as \"Reserved,\" you are required to pay the Token Advance of 10,000 within the next 72 hours via the NestFind App.")
    pdf.ln(10)
    
    # Transaction Details Table
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 10, "TRANSACTION DETAILS:", 0, 1)
    pdf.line(10, pdf.get_y(), 100, pdf.get_y()) # Short underline
    pdf.ln(2)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(40, 8, "Property ID:", 0, 0)
    pdf.cell(0, 8, f"#{property_id}", 0, 1)
    
    pdf.cell(40, 8, "Agreed Price:", 0, 0)
    pdf.cell(0, 8, f"{amount:,.2f}", 0, 1)
    
    pdf.cell(40, 8, "Token Required:", 0, 0)
    pdf.cell(0, 8, "10,000", 0, 1)
    
    pdf.ln(2)
    pdf.line(10, pdf.get_y(), 100, pdf.get_y())
    pdf.ln(10)
    
    # Closing
    pdf.multi_cell(0, 7, "Once the token is paid, this property will be removed from the public marketplace.")
    pdf.ln(10)
    
    pdf.cell(0, 7, "Sincerely,", 0, 1)
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 7, agent_name, 0, 1)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 7, "Authorized Partner, NestFind", 0, 1)
    
    # Footer Note
    pdf.ln(20)
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, "Valid for 3 Days. Generated by NestFind Secure Cloud.", 0, 1, "C")
    
    filename = f"offer_letter_{property_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"

def generate_receipt(buyer_name, property_title, transaction_id, amount=10000, property_location="[City, State]", agent_name="[Agent Name]", agent_phone="[Agent Phone]"):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    
    # Receipt Header
    pdf.set_font("Arial", "B", 20)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, "PAYMENT RECEIPT", 0, 1, "C")
    
    # Status Stamp
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(34, 197, 94) # Green
    # Draw a box for status
    pdf.rect(150, 35, 45, 10, 'F')
    pdf.set_xy(150, 35)
    pdf.cell(45, 10, "PAID - RESERVED", 0, 1, "C")
    
    pdf.ln(15)
    
    # Receipt Details
    current_time = datetime.now()
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"RECEIPT # {transaction_id}", 0, 1)
    pdf.cell(0, 8, f"Date: {current_time.strftime('%Y-%m-%d')}", 0, 1)
    pdf.cell(0, 8, f"Time: {current_time.strftime('%H:%M:%S')}", 0, 1)
    pdf.ln(10)
    
    pdf.cell(0, 8, "RECEIVED FROM:", 0, 1)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, buyer_name, 0, 1)
    pdf.ln(10)
    
    # Amount Box
    pdf.set_fill_color(250, 250, 250)
    pdf.set_draw_color(0, 0, 0)
    # Draw rect around amount
    pdf.rect(10, pdf.get_y(), 190, 25)
    
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, "AMOUNT RECEIVED:", 0, 1)
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 8, f"{amount:,.2f} (Ten Thousand Rupees Only)", 0, 1)
    pdf.ln(15)
    
    # For Section
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, "FOR:", 0, 1)
    pdf.cell(0, 8, "Token Advance / Reservation Fee", 0, 1)
    pdf.cell(0, 8, f"Property: {property_title}", 0, 1)
    pdf.cell(0, 8, f"Location: {property_location}", 0, 1)
    pdf.ln(5)
    
    pdf.cell(0, 8, "PAYMENT STATUS: SUCCESS", 0, 1)
    pdf.cell(0, 8, "METHOD: NestFind Secure Gateway (Mock)", 0, 1)
    pdf.ln(10)
    
    # Important Note
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", "B", 10)
    pdf.multi_cell(0, 6, "IMPORTANT:")
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, f"This property is now marked as \"RESERVED\" in your name.\nPlease contact your agent {agent_name} at {agent_phone}\nto proceed with the final registration and legal documentation.")
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    
    # Watermark
    pdf.ln(20)
    pdf.set_font("Arial", "B", 30)
    pdf.set_text_color(220, 220, 220)
    pdf.cell(0, 10, "PROPERTY RESERVED", 0, 1, "C")
    
    filename = f"receipt_{transaction_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"

def generate_sale_deed(buyer_name, seller_name, property_title, property_address, sale_price, transaction_id):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    
    # Decorative Border
    pdf.set_line_width(1)
    pdf.rect(5, 5, 200, 287)
    pdf.set_line_width(0.2)
    pdf.rect(7, 7, 196, 283)

    # Header
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, "DEED OF SALE", 0, 1, 'C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Transfer of Property Ownership", 0, 1, 'C')
    pdf.ln(10)

    # Content
    pdf.set_font("Arial", '', 11)
    
    current_date = datetime.now().strftime('%d %B, %Y')
    
    body_text = f"""THIS DEED OF SALE is executed on {current_date} between:

SELLER:
{seller_name}
(Hereinafter referred to as the "Transferor")

AND

BUYER:
{buyer_name}
(Hereinafter referred to as the "Transferee")

WHEREAS the Seller is the absolute owner of the property described below and has agreed to sell the same to the Buyer.

PROPERTY SCHEDULE:
{property_title}
Address: {property_address}

NOW THIS DEED WITNESSES that in pursuance of the said agreement and in consideration of the sum paid, the Seller hereby transfers to the Buyer all rights, title, and interest in the said property.
"""
    pdf.multi_cell(0, 7, body_text)
    pdf.ln(5)

    # Financial Settlement Section
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "FINANCIAL SETTLEMENT:", 0, 1)
    
    pdf.set_font("Arial", '', 11)
    pdf.cell(100, 8, "Total Sale Consideration:", 0, 0)
    pdf.cell(50, 8, f"INR {sale_price:,.2f}", 0, 1, 'R')
    
    pdf.cell(100, 8, "Payment Mode:", 0, 0)
    pdf.cell(50, 8, "NestFind Secure Transfer", 0, 1, 'R')
    
    pdf.cell(100, 8, "Transaction Ref:", 0, 0)
    pdf.cell(50, 8, f"TXN-{transaction_id}", 0, 1, 'R')

    pdf.ln(10)

    # Official Stamp Section
    pdf.set_y(-80)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(90, 10, "Signed and Delivered by:", 0, 0)
    pdf.cell(90, 10, "In the presence of:", 0, 1)
    
    pdf.ln(15)
    pdf.cell(90, 10, "_______________________", 0, 0)
    pdf.cell(90, 10, "_______________________", 0, 1)
    pdf.cell(90, 10, "Seller Signature", 0, 0)
    pdf.cell(90, 10, "NestFind Registrar", 0, 1)

    # Watermark
    pdf.set_font("Arial", 'B', 50)
    pdf.set_text_color(240, 240, 240)
    pdf.set_xy(0, 200)
    pdf.cell(0, 20, "OFFICIAL COPY", 0, 1, 'C')

    filename = f"Sale_Deed_{transaction_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"

def generate_success_fee_receipt(payer_name, property_title, transaction_id, amount, property_location="[City, State]"):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    
    # Receipt Header
    pdf.set_font("Arial", "B", 20)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, "PAYMENT RECEIPT", 0, 1, "C")
    
    # Status Stamp
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(34, 197, 94) # Green
    pdf.rect(150, 35, 45, 10, 'F')
    pdf.set_xy(150, 35)
    pdf.cell(45, 10, "PAID - SUCCESS", 0, 1, "C")
    
    pdf.ln(15)
    
    # Receipt Details
    current_time = datetime.now()
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"RECEIPT # {transaction_id}", 0, 1)
    pdf.cell(0, 8, f"Date: {current_time.strftime('%Y-%m-%d')}", 0, 1)
    pdf.cell(0, 8, f"Time: {current_time.strftime('%H:%M:%S')}", 0, 1)
    pdf.ln(10)
    
    pdf.cell(0, 8, "RECEIVED FROM:", 0, 1)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, payer_name, 0, 1)
    pdf.ln(10)
    
    # Amount Box
    pdf.set_fill_color(250, 250, 250)
    pdf.set_draw_color(0, 0, 0)
    pdf.rect(10, pdf.get_y(), 190, 25)
    
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, "AMOUNT RECEIVED:", 0, 1)
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 8, f"INR {amount:,.2f}", 0, 1)
    pdf.ln(15)
    
    # For Section
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, "FOR:", 0, 1)
    pdf.cell(0, 8, "Success Fee / Platform Commission (0.9%)", 0, 1)
    pdf.cell(0, 8, f"Property: {property_title}", 0, 1)
    pdf.cell(0, 8, f"Location: {property_location}", 0, 1)
    pdf.ln(5)
    
    pdf.cell(0, 8, "PAYMENT STATUS: SUCCESS", 0, 1)
    pdf.cell(0, 8, "METHOD: NestFind Secure Gateway", 0, 1)
    pdf.ln(10)
    
    # Footer
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 6, "Thank you for choosing NestFind. This receipt acknowledges the payment of the success fee for the successful closure of the deal.")
    
    filename = f"success_fee_receipt_{transaction_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"

def generate_final_statement(buyer_name, seller_name, property_title, property_address, sale_price, token_amount, success_fee, transaction_id):
    ensure_upload_dir()
    
    pdf = PDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 22)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, "FINAL SETTLEMENT STATEMENT", 0, 1, "C")
    pdf.ln(10)
    
    # Deal Info
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "DEAL INFORMATION:", 0, 1)
    pdf.line(10, pdf.get_y(), 100, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(40, 8, "Property:", 0, 0)
    pdf.cell(0, 8, property_title, 0, 1)
    pdf.cell(40, 8, "Address:", 0, 0)
    pdf.cell(0, 8, property_address, 0, 1)
    pdf.cell(40, 8, "Date:", 0, 0)
    pdf.cell(0, 8, datetime.now().strftime('%Y-%m-%d'), 0, 1)
    pdf.ln(10)
    
    # Parties
    pdf.set_font("Arial", "B", 12)
    pdf.cell(90, 8, "SELLER", 0, 0)
    pdf.cell(90, 8, "BUYER", 0, 1)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(90, 6, seller_name, 0, 0)
    pdf.cell(90, 6, buyer_name, 0, 1)
    pdf.ln(10)
    
    # Financial Breakdown
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "FINANCIAL BREAKDOWN:", 0, 1)
    pdf.set_fill_color(240, 240, 240)
    pdf.rect(10, pdf.get_y(), 190, 8, 'F')
    pdf.cell(140, 8, "Description", 1, 0, 'L')
    pdf.cell(50, 8, "Amount (INR)", 1, 1, 'R')
    
    pdf.set_font("Arial", "", 11)
    
    # Rows
    items = [
        ("Sale Price", sale_price),
        ("Booking Token (Paid by Buyer)", token_amount),
        ("Success Fee (Paid by Seller/Agent)", success_fee),
    ]
    
    for desc, amt in items:
        pdf.cell(140, 8, desc, 1, 0, 'L')
        pdf.cell(50, 8, f"{amt:,.2f}", 1, 1, 'R')
        
    pdf.ln(5)
    
    # Net to Seller
    net_seller = sale_price - success_fee
    pdf.set_font("Arial", "B", 12)
    pdf.cell(140, 10, "NET TO SELLER:", 0, 0, 'R')
    pdf.cell(50, 10, f"{net_seller:,.2f}", 1, 1, 'R')
    
    pdf.ln(20)
    
    # Signatures
    pdf.cell(90, 10, "_______________________", 0, 0)
    pdf.cell(90, 10, "_______________________", 0, 1)
    pdf.cell(90, 10, "Seller Signature", 0, 0)
    pdf.cell(90, 10, "Buyer Signature", 0, 1)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, f"Statement ID: STMT-{transaction_id} | Generated by NestFind", 0, 1, "C")
    
    filename = f"final_statement_{transaction_id}_{int(datetime.now().timestamp())}.pdf"
    filepath = os.path.join(UPLOAD_DIR, filename)
    pdf.output(filepath)
    
    return f"/uploads/documents/{filename}"
